services:
  - type: web
    name: plantpal
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: plantpal-db
          property: connectionString
      - key: LOCAL_DB_URL
        fromDatabase:
          name: plantpal-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false

databases:
  - name: plantpal-db
    plan: free
    databaseName: plantpal
